complain if the png HID has been requested but all formats disabled

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4357,6 +4357,23 @@ echo "$as_me: error: $e is not a valid exporter" >&2;}
     esac
 done
 
+if test "X$enable_jpeg" = "Xno" -a "X$enable_gif" = "Xno" -a "X$enable_png" = "Xno" ; then
+	case " ${HIDLIST} " in
+		*\ png\ *)
+			{ { echo "$as_me:$LINENO: error: you have requested the png HID but turned off all output
+formats!  If you do not want gif/jpeg/png output, use --with-exporters to list
+which exporters you want and do not list png there." >&5
+echo "$as_me: error: you have requested the png HID but turned off all output
+formats!  If you do not want gif/jpeg/png output, use --with-exporters to list
+which exporters you want and do not list png there." >&2;}
+   { (exit 1); exit 1; }; }
+			;;
+
+		*)
+			;;
+	esac
+fi
+
 for e in $HIDLIST; do
     HIDLIBS="$HIDLIBS lib$e.a"
 done
