regen

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7013,23 +7013,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for gtk+-2.0 >= 2.2.0" >&5
-echo $ECHO_N "checking for gtk+-2.0 >= 2.2.0... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for gtk+-2.0 >= 2.4.0" >&5
+echo $ECHO_N "checking for gtk+-2.0 >= 2.4.0... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "gtk+-2.0 >= 2.2.0" ; then
+        if $PKG_CONFIG --exists "gtk+-2.0 >= 2.4.0" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking GTK_CFLAGS" >&5
 echo $ECHO_N "checking GTK_CFLAGS... $ECHO_C" >&6
-            GTK_CFLAGS=`$PKG_CONFIG --cflags "gtk+-2.0 >= 2.2.0"`
+            GTK_CFLAGS=`$PKG_CONFIG --cflags "gtk+-2.0 >= 2.4.0"`
             echo "$as_me:$LINENO: result: $GTK_CFLAGS" >&5
 echo "${ECHO_T}$GTK_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking GTK_LIBS" >&5
 echo $ECHO_N "checking GTK_LIBS... $ECHO_C" >&6
-            GTK_LIBS=`$PKG_CONFIG --libs "gtk+-2.0 >= 2.2.0"`
+            GTK_LIBS=`$PKG_CONFIG --libs "gtk+-2.0 >= 2.4.0"`
             echo "$as_me:$LINENO: result: $GTK_LIBS" >&5
 echo "${ECHO_T}$GTK_LIBS" >&6
         else
@@ -7037,7 +7037,7 @@ echo "${ECHO_T}$GTK_LIBS" >&6
             GTK_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            GTK_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "gtk+-2.0 >= 2.2.0"`
+            GTK_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "gtk+-2.0 >= 2.4.0"`
 
         fi
 
@@ -7052,8 +7052,8 @@ echo "${ECHO_T}$GTK_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Cannot find gtk+ >= 2.2.0, install it and rerun ./configure" >&5
-echo "$as_me: error: Cannot find gtk+ >= 2.2.0, install it and rerun ./configure" >&2;}
+     { { echo "$as_me:$LINENO: error: Cannot find gtk+ >= 2.4.0, install it and rerun ./configure" >&5
+echo "$as_me: error: Cannot find gtk+ >= 2.4.0, install it and rerun ./configure" >&2;}
    { (exit 1); exit 1; }; }
 
   fi
@@ -7115,23 +7115,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for glib-2.0 >= 2.2.0" >&5
-echo $ECHO_N "checking for glib-2.0 >= 2.2.0... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for glib-2.0 >= 2.4.0" >&5
+echo $ECHO_N "checking for glib-2.0 >= 2.4.0... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "glib-2.0 >= 2.2.0" ; then
+        if $PKG_CONFIG --exists "glib-2.0 >= 2.4.0" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking GLIB_CFLAGS" >&5
 echo $ECHO_N "checking GLIB_CFLAGS... $ECHO_C" >&6
-            GLIB_CFLAGS=`$PKG_CONFIG --cflags "glib-2.0 >= 2.2.0"`
+            GLIB_CFLAGS=`$PKG_CONFIG --cflags "glib-2.0 >= 2.4.0"`
             echo "$as_me:$LINENO: result: $GLIB_CFLAGS" >&5
 echo "${ECHO_T}$GLIB_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking GLIB_LIBS" >&5
 echo $ECHO_N "checking GLIB_LIBS... $ECHO_C" >&6
-            GLIB_LIBS=`$PKG_CONFIG --libs "glib-2.0 >= 2.2.0"`
+            GLIB_LIBS=`$PKG_CONFIG --libs "glib-2.0 >= 2.4.0"`
             echo "$as_me:$LINENO: result: $GLIB_LIBS" >&5
 echo "${ECHO_T}$GLIB_LIBS" >&6
         else
@@ -7139,7 +7139,7 @@ echo "${ECHO_T}$GLIB_LIBS" >&6
             GLIB_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            GLIB_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glib-2.0 >= 2.2.0"`
+            GLIB_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glib-2.0 >= 2.4.0"`
 
         fi
 
@@ -7154,8 +7154,8 @@ echo "${ECHO_T}$GLIB_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Cannot find glib >= 2.2.0, install it and rerun ./configure." >&5
-echo "$as_me: error: Cannot find glib >= 2.2.0, install it and rerun ./configure." >&2;}
+     { { echo "$as_me:$LINENO: error: Cannot find glib >= 2.4.0, install it and rerun ./configure." >&5
+echo "$as_me: error: Cannot find glib >= 2.4.0, install it and rerun ./configure." >&2;}
    { (exit 1); exit 1; }; }
 
   fi
