copy over build_pcb improvements from gerbv.  Add gdwin32 to the extract script.

diff --git a/win32/build_pcb b/win32/build_pcb
--- a/win32/build_pcb
+++ b/win32/build_pcb
@@ -27,9 +27,15 @@ Supported options:
                   - Pass "--enable-maintainer-mode" to the
                     configure script.
 
+
   --help          - Show this message and exit.
 
+  --force-autogen - Force running ./autogen.sh.  Normally this is
+                    only done if the configure script is not present.
+
   --skip-build    - Skip the "make" step of the process.
+
+  --skip-clean    - Skip the "make clean" step of the process.
 
   --skip-config   - Skip the "./configure" step of the process.
 
@@ -45,9 +51,12 @@ EOF
 }
 
 debug=no
+do_autogen=no
 do_config=yes
 do_build=yes
+do_clean=yes
 do_install=yes
+config_args=""
 while test $# -ne 0 ; do
 	case $1 in
 		--debug)
@@ -55,23 +64,33 @@ while test $# -ne 0 ; do
 			shift
 			;;
 
-		--disable-doc)
-			config_args="${config_args} --disable-doc"
-			shift
-			;;
+               --disable-doc)
+                       config_args="${config_args} --disable-doc"
+                       shift
+                       ;;
 
-		--enable-maintainer-mode)
-			config_args="${config_args} --enable-maintainer-mode"
-			shift
-			;;
+               --enable-maintainer-mode)
+                       config_args="${config_args} --enable-maintainer-mode"
+                       shift
+                       ;;
 
 		--help)
 			usage
 			exit 0
 			;;
 
+		--force-autogen)
+			do_autogen=yes
+			shift
+			;;
+
 		--skip-build)
 			do_build=no
+			shift
+			;;
+
+		--skip-clean)
+			do_clean=no
 			shift
 			;;
 
@@ -97,6 +116,11 @@ while test $# -ne 0 ; do
 	esac
 done
 
+if test ! -f win32/build_pcb ; then
+	echo "$0:  ERROR.  This script must be run from the top level of the pcb source tree."
+	exit 1
+fi
+
 # Run this under cygwin to build pcb and create a windows installer for
 # it.  Thanks to Bob Paddock for pointing me to NSIS and answering some 
 # beginner windows questions.
@@ -107,15 +131,17 @@ gtk_win32=c:\\cygwin\\home\\${USER}\\gtk_win32
 # where only the runtime components are installed
 gtk_win32_runtime=c:\\\\cygwin\\\\home\\\\${USER}\\\\gtk_win32_runtime
 
+
 # where the gdwin32.zip archive has been extracted
 # gdwin32.zip can be downloaded from http://www.boutell.com/gd/http/gdwin32.zip
 # I have used 2.0.33
 gd_win32=c:\\cygwin\\home\\${USER}\\gdwin32
 gd_win32_runtime=c:\\\\cygwin\\\\home\\\\${USER}\\\\gdwin32
 
+
 # pcb version
 
-pcb_version=`awk '/AM_INIT_AUTOMAKE/ {gsub(/.*,[ \t]*/, ""); gsub(/\).*/, ""); print}' configure.ac `
+pcb_version=`awk '/AC_INIT/ {gsub(/.*,[ \t]*\[/, ""); gsub(/\]\).*/, ""); print}' configure.ac`
 echo "pcb_version=${pcb_version}"
 
 # location of the NSIS makensis executible (see http://nsis.sourceforge.net)
@@ -128,6 +154,11 @@ makensis="/cygdrive/c/Program Files/NSIS/makensis.exe"
 #
 # ########################################################################
 
+
+if test ! -f configure -o $do_autogen = yes ; then
+	echo "Bootstrapping autotools"
+	ACLOCAL_FLAGS="-I ${gtk_win32}\\share\\aclocal" ./autogen.sh
+fi
 
 # source directory
 srcdir=`pwd.exe`/win32
@@ -152,6 +183,14 @@ export PATH
 echo "Showing packages known to pkg-config:"
 pkg-config --list-all
 
+
+# do not try to use libpng-config, it seems broken on win32
+LIBPNG_CONFIG=/usr/bin/true
+export LIBPNG_CONFIG
+LIBPNG_CFLAGS="-I${HOME}/gtk_win32/include"
+LIBPNG_LDFLAGS="-L${HOME}/gtk_win32/lib"
+LIBPNG_LIBS="-lpng"
+
 # do not try and build the tk based QFP footprint
 # builder
 WISH=/usr/bin/true
@@ -161,7 +200,7 @@ export WISH
 # configure gdlib
 GDLIB_CONFIG=/usr/bin/true
 export GDLIB_CONFIG
-
+ 
 GDLIB_CFLAGS="-I${HOME}/gdwin32"
 GDLIB_LDFLAGS="-L${HOME}/gdwin32"
 
@@ -180,19 +219,22 @@ export CYGWIN_CPPFLAGS
 # setting WIN32=yes will make sure that the desktop icon
 # gets compiled in
 if test "$do_config" = "yes" ; then
+rm -fr src/.deps
 echo "Configuring for cygwin"
 ( ( ( env WIN32=yes \
-	ac_cv_func_gdImageGif="yes" \
-	ac_cv_func_gdImageJpeg="yes" \
-	ac_cv_func_gdImagePng="yes" \
 	./configure \
 	--prefix=${pcb_inst} \
+       ac_cv_func_gdImageGif="yes" \
+       ac_cv_func_gdImageJpeg="yes" \
+       ac_cv_func_gdImagePng="yes" \
+	--disable-dependency-tracking \
 	--disable-nls \
-	--with-exporters="bom gerber ps png" \
-	--with-printer="" \
+	--disable-update-desktop-database \
+	--disable-update-mime-database \
 	${config_args} \
-	CFLAGS="${GDLIB_CFLAGS}" \
-	LDFLAGS="${GDLIB_LDFLAGS}" \
+        CFLAGS="${GDLIB_CFLAGS}" \
+        LDFLAGS="${GDLIB_LDFLAGS}" \
+	WIN32=yes \
 	2>&1 ; echo $? >&4 ) | tee c.log 1>&3) 4>&1 | (read a ; exit $a)) 3>&1
 
 if test $? -ne 0 ; then
@@ -200,6 +242,19 @@ if test $? -ne 0 ; then
 	exit 1
 fi
 
+# If the win32 pkg-config is used, then you end up with spurious CR's
+# in the generated Makefile's and we need to get rid of them.
+dos2unix src/Makefile
+
+fi
+
+if test "$do_clean" = "yes" ; then
+echo "Cleaning"
+( ( ( make clean 2>&1 ; echo $? >&4) | tee clean.log 1>&3) 4>&1 | (read a ; exit $a) ) 3>&1
+if test $? -ne 0 ; then
+	echo "**** ERROR **** Clean failed. See log in clean.log"
+	exit 1
+fi
 fi
 
 if test "$do_build" = "yes" ; then
@@ -236,6 +291,7 @@ sed \
 	-e "s;@pcb_prefix@;${pcb_inst_dir};g" \
 	-e "s;@pcb_srcdir@;${top_src_dir};g" \
 	-e "s;@gtk_win32_runtime@;${gtk_win32_runtime};g" \
+	-e "s;@gd_win32@;${gd_win32};g" \
 	-e "s;@gd_win32_runtime@;${gd_win32_runtime};g" \
 	${srcdir}/pcb.nsi.in > ${srcdir}/pcb.nsi
 
