if the configure or build fails, then abort the whole process.

diff --git a/win32/build_pcb b/win32/build_pcb
--- a/win32/build_pcb
+++ b/win32/build_pcb
@@ -73,21 +73,34 @@ export CYGWIN_CPPFLAGS
 # gets compiled in
 if test "$do_config" = "yes" ; then
 echo "Configuring for cygwin"
-env WIN32=yes ./configure \
+( ( ( env WIN32=yes ./configure \
 	--prefix=${pcb_inst} \
 	--disable-nls \
 	--with-exporters="bom gerber ps" \
 	--with-printer="" \
-	2>&1 | tee c.log
+	2>&1 ; echo $? >&4 ) | tee c.log 1>&3) 4>&1 | (read a ; exit $a)) 3>&1
+
+if test $? -ne 0 ; then
+	echo "**** ERROR **** Configure failed. See log in c.log"
+	exit 1
+fi
 
 fi
 
 if test "$do_build" = "yes" ; then
 echo "Building for cygwin"
-make 2>&1 | tee m.log
+( ( ( make 2>&1 ; echo $? >&4) | tee m.log 1>&3) 4>&1 | (read a ; exit $a) ) 3>&1
+if test $? -ne 0 ; then
+	echo "**** ERROR **** Build failed. See log in m.log"
+	exit 1
+fi
 
 echo "Installing for cygwin"
-make install 2>&1 | tee -a m.log
+( ( ( make install 2>&1 ; echo $? >&4) | tee -a m.log 1>&3) 4>&1 | (read a ; exit $a) ) 3>&1
+if test $? -ne 0 ; then
+	echo "**** ERROR **** Build failed. See log in m.log"
+	exit 1
+fi
 
 fi
 
