get rid of an insecure usage of a temp file

diff --git a/src/pcbtest.sh.in b/src/pcbtest.sh.in
--- a/src/pcbtest.sh.in
+++ b/src/pcbtest.sh.in
@@ -42,10 +42,18 @@ TEST_CMDS="--lib-command-dir @TOP_BUILDDIR@/lib"
 
 if [ "X$1" = "X-gdb" ]; then
 	shift
-	tmpf=/tmp/pcbtest.gdb.$$
+	tmpd=/tmp/pcbtest.$$
+	tmpf=${tmpd}/pcbtest.gdb
+	mkdir -p -m 0700 ${tmpd}
+	rc=$?
+	if test $rc -ne 0 ; then
+		echo "$0:  Could not create ${tmpd} with mode = 0700"
+	 	echo "   mkdir returned $rc"
+		exit 1
+	fi
 	echo set args $TEST_PATHS $TEST_CMDS "$@"  > $tmpf
 	exec gdb -x $tmpf ./pcb
-	rm -f $tmpf
+	rm -fr $tmpd
 else
 	exec ./pcb $TEST_PATHS $TEST_CMDS "$@"
 fi
